"""Entry point for the ``sectum`` command-line interface (the engineering spec, section 10).

Implemented: ``--version``, ``adapters``, ``seed``, ``probe``, ``report``,
``verify``, ``erasure``, ``init``, and ``baseline``.
"""

import functools
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Annotated
from uuid import UUID

import typer

from sectum.adapters import (
    AdapterRegistry,
    FakeAgent,
    FakeCache,
    FakeMCP,
    FakeMemory,
    FakeModel,
    FakeObservability,
    FakeRAGPipeline,
    FakeVectorStore,
)
from sectum.baseline import compare_metrics
from sectum.config import AdapterConfig, SectumConfig, build_adapters, load_config
from sectum.evidence import (
    build_evidence_pack,
    control_mappings,
    render_audit_pack,
    verify_pack,
)
from sectum.probes import (
    AgentToolHijackProbe,
    EmbeddingInversionProbe,
    ErasureProbe,
    IkeaExtractionProbe,
    KvCacheTimingProbe,
    LoraCrossTenantProbe,
    MemoryContamProbe,
    Probe,
    RagEntityBleedProbe,
    RagPoisoningProbe,
    SemanticCacheProbe,
    TenantBoundaryProbe,
    confirmed_findings,
    dedupe_findings,
)
from sectum.runner import Runner, StepResult, retrieval_pivot_rate
from sectum.spec import (
    EvidenceError,
    EvidencePack,
    Finding,
    MarkerType,
    RunMetrics,
    RunResult,
    SectumError,
    Substrate,
    canonical_hash,
)
from sectum.substrate import build_substrate, default_scenario

__version__ = "0.0.0"

_DEFAULT_WORKDIR = Path(".sectum")
_DEFAULT_CONFIG = Path("sectum.yaml")
_SUITE: tuple[Probe, ...] = (
    TenantBoundaryProbe(),
    RagEntityBleedProbe(),
    SemanticCacheProbe(),
    LoraCrossTenantProbe(),
    AgentToolHijackProbe(),
    MemoryContamProbe(),
    EmbeddingInversionProbe(),
    IkeaExtractionProbe(),
    RagPoisoningProbe(),
)

# The CLI's default for `sectum probe`: every fake's leak knob is on, so the
# probe suite reproduces the cross-tenant findings the probes are built to
# catch. Override by passing `--config sectum.yaml`.
_DEMO_CONFIG = SectumConfig(
    adapters={
        "vector_store": AdapterConfig(kind="fake", shared_index=True),
        "cache": AdapterConfig(kind="fake", tenant_scoped=False),
        "model": AdapterConfig(kind="fake", adapter_bleed=True, prefix_cache=True),
        "mcp": AdapterConfig(kind="fake", confused_deputy=True, token_passthrough=True),
        "memory": AdapterConfig(kind="fake", shared_memory=True),
    }
)

_CONFIG_TEMPLATE = """\
# Sectum AI configuration - see https://docs.sectum.ai
# Generated by `sectum init`. Edit it to point Sectum AI at the stack to verify.

# How the synthetic tenants and their corpora are generated.
scenario:
  seed: 2026
  corpus_profile: demo

# Where run artifacts are written (substrate, run, evidence pack, audit pack).
workdir: .sectum

# Adapters connecting Sectum AI to the stack under test. The defaults are the
# in-memory fakes with their leak knobs turned on - so `sectum probe` reproduces
# the cross-tenant findings the probes are built to catch. Turn the knobs off
# (or point at a live backend) to verify a tenant-isolated stack. Never inline
# credentials - reference them from the environment.
adapters:
  vector_store:
    kind: fake               # fake | pgvector | chroma | weaviate
    shared_index: true       # demo leak: one index serves every tenant
    # dsn_env: SECTUM_PGVECTOR_DSN
  cache:
    kind: fake               # fake | redis
    tenant_scoped: false     # demo leak: a shared key space across tenants
  model:
    kind: fake
    adapter_bleed: true      # demo leak: one tenant's adapter influences others
    prefix_cache: true       # demo leak: a shared KV prefix cache leaks via timing
  mcp:
    kind: fake               # fake | stdio
    confused_deputy: true    # demo leak: the MCP server lost tenant scope
    token_passthrough: true  # demo leak: the server trusts a caller-supplied token
  memory:
    kind: fake
    shared_memory: true      # demo leak: long-term memory crosses tenants

# Evidence-chain anchoring. The local timestamper is the development default;
# production configures an RFC 3161 TSA and a Sigstore Rekor instance.
evidence:
  timestamper: local    # local | rfc3161
  # tsa_url: https://freetsa.org/tsr
  # rekor_url: https://rekor.sigstore.dev
"""

app = typer.Typer(
    name="sectum",
    help="Sectum AI - multi-tenant AI verification.",
    no_args_is_help=True,
    add_completion=False,
)


def _handle_typed_errors[**P, R](func: Callable[P, R]) -> Callable[P, R]:
    """Translate a ``SectumError`` raised inside a command into the section-10 exit code.

    An ``EvidenceError`` exits with code 4 (evidence verification failure); any
    other ``SectumError`` exits with code 3 (config/adapter error). Other
    exceptions propagate unchanged.
    """

    @functools.wraps(func)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
        try:
            return func(*args, **kwargs)
        except EvidenceError as error:
            typer.echo(f"{type(error).__name__}: {error}", err=True)
            raise typer.Exit(code=4) from error
        except SectumError as error:
            typer.echo(f"{type(error).__name__}: {error}", err=True)
            raise typer.Exit(code=3) from error

    return wrapper


def _version_callback(value: bool) -> None:
    """Print the CLI version and exit when ``--version`` is passed."""
    if value:
        typer.echo(f"sectum {__version__}")
        raise typer.Exit


@app.callback()
def main(
    version: Annotated[
        bool,
        typer.Option(
            "--version",
            help="Show the Sectum AI CLI version and exit.",
            callback=_version_callback,
            is_eager=True,
        ),
    ] = False,
) -> None:
    """Sectum AI - multi-tenant AI verification."""


@app.command(name="adapters")
def list_adapters() -> None:
    """List the installed adapters and their capabilities."""
    registry = AdapterRegistry()
    for fake in (
        FakeVectorStore(),
        FakeRAGPipeline(),
        FakeObservability(),
        FakeAgent(),
        FakeMCP(),
        FakeCache(),
        FakeModel(),
        FakeMemory(),
    ):
        registry.register(fake)
    typer.echo(f"{'ADAPTER':<22}{'FAMILY':<18}CAPABILITIES")
    for adapter in registry.all():
        capabilities = ", ".join(sorted(c.value for c in adapter.capabilities)) or "(none)"
        typer.echo(f"{adapter.name:<22}{adapter.family.value:<18}{capabilities}")


def _load_substrate(workdir: Path) -> Substrate:
    """Load the seeded substrate from ``workdir``, or exit with a config error."""
    path = workdir / "substrate.json"
    if not path.exists():
        typer.echo(f"no substrate at {path}; run 'sectum seed' first", err=True)
        raise typer.Exit(code=3)
    return Substrate.model_validate_json(path.read_text())


def _load_run(workdir: Path) -> RunResult:
    """Load the recorded run from ``workdir``, or exit with a config error."""
    path = workdir / "run.json"
    if not path.exists():
        typer.echo(f"no run at {path}; run 'sectum probe' first", err=True)
        raise typer.Exit(code=3)
    return RunResult.model_validate_json(path.read_text())


def _per_probe_counts(findings: list[Finding]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for finding in findings:
        counts[finding.probe_id] = counts.get(finding.probe_id, 0) + 1
    return counts


def _resolve_target(substrate: Substrate, name: str | None) -> UUID:
    """Resolve a target tenant by display name, defaulting to the first tenant."""
    if name is None:
        return substrate.tenants[0].tenant_id
    for tenant in substrate.tenants:
        if tenant.display_name.lower() == name.lower():
            return tenant.tenant_id
    available = ", ".join(tenant.display_name for tenant in substrate.tenants)
    typer.echo(f"unknown tenant '{name}'; available: {available}", err=True)
    raise typer.Exit(code=3)


@app.command()
@_handle_typed_errors
def seed(
    scenario_seed: Annotated[int | None, typer.Option("--seed", help="Scenario seed.")] = None,
    workdir: Annotated[Path | None, typer.Option(help="Directory for run artifacts.")] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Provision synthetic tenants, generate corpora, and plant canary markers."""
    loaded = load_config(config) if config is not None else SectumConfig()
    effective_seed = scenario_seed if scenario_seed is not None else loaded.scenario.seed
    effective_workdir = workdir if workdir is not None else loaded.workdir
    substrate = build_substrate(default_scenario(seed=effective_seed))
    effective_workdir.mkdir(parents=True, exist_ok=True)
    path = effective_workdir / "substrate.json"
    path.write_text(substrate.model_dump_json(indent=2))
    typer.echo(
        f"seeded {len(substrate.tenants)} tenants and "
        f"{len(substrate.documents)} documents -> {path}"
    )


@app.command()
@_handle_typed_errors
def probe(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the seeded substrate.")
    ] = None,
    only: Annotated[
        str | None, typer.Option("--probe", help="Run only the probe with this id.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read adapters and workdir from this sectum.yaml file."),
    ] = None,
) -> None:
    """Run the probe suite against the configured stack and record the findings."""
    loaded = load_config(config) if config is not None else _DEMO_CONFIG
    effective_workdir = workdir if workdir is not None else loaded.workdir
    substrate = _load_substrate(effective_workdir)
    suite = _SUITE
    run_kv_timing = True
    if only is not None:
        available = [instance.id for instance in _SUITE] + [KvCacheTimingProbe.id]
        if only not in available:
            typer.echo(f"unknown probe '{only}'; available: {', '.join(available)}", err=True)
            raise typer.Exit(code=3)
        suite = tuple(instance for instance in _SUITE if instance.id == only)
        run_kv_timing = only == KvCacheTimingProbe.id
    bundle = build_adapters(loaded)
    vector = bundle.vector
    cache = bundle.cache
    model = bundle.model
    mcp = bundle.mcp
    memory = bundle.memory
    for tenant in substrate.tenants:
        documents = [doc for doc in substrate.documents if doc.tenant_id == tenant.tenant_id]
        vector.upsert(tenant.tenant_id, documents)
    if isinstance(mcp, FakeMCP):
        for marker in substrate.manifest.markers:
            if marker.marker_type is MarkerType.HARD_CANARY:
                mcp.provision(
                    marker.owner_tenant_id,
                    marker.marker_id,
                    f"MCP resource. Reference: {marker.plaintext}",
                )
    runner = Runner(substrate, vector=vector, cache=cache, model=model, mcp=mcp, memory=memory)

    started = datetime.now(UTC)
    step_results: list[StepResult] = []
    for probe_instance in suite:
        step_results.extend(runner.run_per_step(probe_instance))
    kv_report = KvCacheTimingProbe(substrate, model=model).run() if run_kv_timing else None
    finished = datetime.now(UTC)

    suite_findings = [finding for _, group in step_results for finding in group]
    kv_findings = list(kv_report.findings) if kv_report is not None else []
    findings = tuple(dedupe_findings([*suite_findings, *kv_findings]))
    confirmed = confirmed_findings(findings)
    bleed_steps = [
        result for result in step_results if result[0].probe_id == RagEntityBleedProbe.id
    ]
    run = RunResult(
        run_id=f"run-{substrate.scenario.scenario_id}",
        scenario_hash=canonical_hash(substrate.scenario),
        manifest_hash=canonical_hash(substrate.manifest),
        started_at=started,
        finished_at=finished,
        adapter_versions={
            vector.name: __version__,
            cache.name: __version__,
            model.name: __version__,
            mcp.name: __version__,
            memory.name: __version__,
        },
        probe_versions={
            **{instance.id: __version__ for instance in suite},
            **({KvCacheTimingProbe.id: __version__} if run_kv_timing else {}),
        },
        findings=findings,
        metrics=RunMetrics(
            confirmed_findings=len(confirmed),
            retrieval_pivot_rate=retrieval_pivot_rate(bleed_steps) if bleed_steps else None,
            per_probe_findings=_per_probe_counts(confirmed),
            side_channel_effect_sizes=kv_report.effect_sizes if kv_report is not None else {},
        ),
    )
    path = effective_workdir / "run.json"
    path.write_text(run.model_dump_json(indent=2))
    probe_count = len(suite) + (1 if run_kv_timing else 0)
    plural = "" if probe_count == 1 else "s"
    typer.echo(f"ran {probe_count} probe{plural}: {len(confirmed)} confirmed cross-tenant findings")
    if run.metrics.retrieval_pivot_rate is not None:
        typer.echo(f"retrieval-pivot rate: {run.metrics.retrieval_pivot_rate:.0%}")
    typer.echo(f"run recorded -> {path}")
    if confirmed:
        raise typer.Exit(code=2)


@app.command()
@_handle_typed_errors
def report(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the substrate and run.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Assemble a tamper-evident evidence pack (JSON and PDF) from the run."""
    loaded = load_config(config) if config is not None else SectumConfig()
    if workdir is None:
        workdir = loaded.workdir
    substrate = _load_substrate(workdir)
    run = _load_run(workdir)
    pack = build_evidence_pack(run, substrate.manifest, control_mappings=control_mappings())
    json_path = workdir / "evidence.json"
    json_path.write_text(pack.model_dump_json(indent=2))
    pdf_path = workdir / "audit-pack.pdf"
    render_audit_pack(pack, pdf_path)
    typer.echo(f"evidence pack -> {json_path}")
    typer.echo(f"audit pack -> {pdf_path}")


@app.command()
def verify(
    pack: Annotated[Path, typer.Argument(help="Path to an evidence.json pack.")],
) -> None:
    """Independently verify a tamper-evident evidence pack."""
    if not pack.exists():
        typer.echo(f"no evidence pack at {pack}", err=True)
        raise typer.Exit(code=3)
    evidence = EvidencePack.model_validate_json(pack.read_text())
    result = verify_pack(evidence)
    for check in result.checks:
        typer.echo(f"[{'ok' if check.ok else 'FAIL'}] {check.name}: {check.detail}")
    if not result.passed:
        typer.echo("VERIFICATION FAILED", err=True)
        raise typer.Exit(code=4)
    typer.echo("VERIFIED: the evidence pack is intact")


@app.command()
@_handle_typed_errors
def erasure(
    target_tenant: Annotated[
        str | None, typer.Option("--target-tenant", help="Tenant display name.")
    ] = None,
    soft_delete: Annotated[
        bool, typer.Option("--soft-delete", help="Model a store that fails erasure.")
    ] = False,
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the seeded substrate.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Run the GDPR Article 17 erasure-verification workflow (Class 11, the wedge)."""
    loaded = load_config(config) if config is not None else SectumConfig()
    if workdir is None:
        workdir = loaded.workdir
    substrate = _load_substrate(workdir)
    target = _resolve_target(substrate, target_tenant)
    store = FakeVectorStore(soft_delete=soft_delete)
    for tenant in substrate.tenants:
        documents = [doc for doc in substrate.documents if doc.tenant_id == tenant.tenant_id]
        store.upsert(tenant.tenant_id, documents)

    started = datetime.now(UTC)
    report = ErasureProbe(substrate, vector=store).run(target)
    finished = datetime.now(UTC)

    run = RunResult(
        run_id=f"erasure-{target.hex[:8]}",
        scenario_hash=canonical_hash(substrate.scenario),
        manifest_hash=canonical_hash(substrate.manifest),
        started_at=started,
        finished_at=finished,
        adapter_versions={store.name: __version__},
        probe_versions={ErasureProbe.id: __version__},
        findings=report.findings,
        metrics=RunMetrics(
            confirmed_findings=len(report.findings),
            erasure_residue={
                surface.surface.value: surface.residual_after for surface in report.surfaces
            },
        ),
    )
    pack = build_evidence_pack(run, substrate.manifest, control_mappings=control_mappings())
    json_path = workdir / "erasure-evidence.json"
    json_path.write_text(pack.model_dump_json(indent=2))
    pdf_path = workdir / "erasure-attestation.pdf"
    render_audit_pack(pack, pdf_path)

    for surface in report.surfaces:
        typer.echo(
            f"{surface.surface.value}: {surface.markers_before} markers before, "
            f"{surface.residual_after} after -> {surface.verdict}"
        )
    typer.echo(f"erasure attestation -> {json_path}, {pdf_path}")
    if report.erased:
        scanned = ", ".join(surface.surface.value for surface in report.surfaces)
        typer.echo(f"ERASURE VERIFIED: no residual marker on {scanned}.")
        return
    if any(surface.residual_after > 0 for surface in report.surfaces):
        typer.echo("ERASURE FAILED: residual data remains.", err=True)
        raise typer.Exit(code=2)
    typer.echo(
        "ERASURE INCONCLUSIVE: the target tenant's markers were not found, "
        "so erasure cannot be attested.",
        err=True,
    )
    raise typer.Exit(code=3)


@app.command()
def init(
    output: Annotated[
        Path, typer.Option(help="Path for the generated config file.")
    ] = _DEFAULT_CONFIG,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite an existing config file.")
    ] = False,
) -> None:
    """Scaffold a sectum.yaml configuration file."""
    if output.exists() and not force:
        typer.echo(f"{output} already exists; pass --force to overwrite", err=True)
        raise typer.Exit(code=3)
    output.write_text(_CONFIG_TEMPLATE)
    typer.echo(f"wrote {output}")


@app.command()
def baseline(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the recorded run.")
    ] = None,
    save: Annotated[
        bool, typer.Option("--save", help="Save the current run's metrics as the baseline.")
    ] = False,
    compare: Annotated[
        bool,
        typer.Option("--compare", help="Compare the current run against the saved baseline."),
    ] = False,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Save a regression baseline from the current run, or compare against it."""
    loaded = load_config(config) if config is not None else SectumConfig()
    if workdir is None:
        workdir = loaded.workdir
    run = _load_run(workdir)
    baseline_path = workdir / "baseline.json"
    if save:
        baseline_path.write_text(run.metrics.model_dump_json(indent=2))
        typer.echo(f"baseline saved -> {baseline_path}")
        return
    if not compare:
        typer.echo("pass --save to record a baseline or --compare to check against it", err=True)
        raise typer.Exit(code=3)
    if not baseline_path.exists():
        typer.echo(f"no baseline at {baseline_path}; run 'sectum baseline --save' first", err=True)
        raise typer.Exit(code=3)
    saved = RunMetrics.model_validate_json(baseline_path.read_text())
    comparison = compare_metrics(saved, run.metrics)
    for delta in comparison.deltas:
        verdict = "REGRESSED" if delta.regressed else "ok"
        typer.echo(f"[{verdict}] {delta.name}: {delta.baseline:g} -> {delta.current:g}")
    if comparison.regressed:
        typer.echo("BASELINE REGRESSION: a metric moved in the worse direction.", err=True)
        raise typer.Exit(code=2)
    typer.echo("no regression against the baseline")


if __name__ == "__main__":  # pragma: no cover
    app()
