"""Entry point for the ``sectum`` command-line interface (the engineering spec, section 10).

Implemented: ``--version``, ``adapters``, ``seed``, ``probe``, ``report``,
``verify``, ``erasure``, ``init``, ``baseline``, and ``diff``.
"""

import functools
import json
from collections.abc import Callable
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Annotated
from uuid import UUID

import typer
from pydantic import ValidationError

from sectum.adapters import (
    AdapterRegistry,
    FakeAgent,
    FakeCache,
    FakeEvalSet,
    FakeMCP,
    FakeMemory,
    FakeModel,
    FakeObservability,
    FakeRAGPipeline,
    FakeSearchIndex,
    FakeVectorStore,
)
from sectum.baseline import FindingChange, MetricDelta, RunDiff, diff_runs
from sectum.config import (
    AdapterConfig,
    EvidenceConfig,
    SectumConfig,
    SecurityConfig,
    build_adapters,
    build_cache,
    build_detection_providers,
    build_memory,
    build_model,
    build_observability,
    build_vector_store,
    load_config,
)
from sectum.crypto import load_key_from_env, seal_bytes, unseal_bytes
from sectum.evidence import (
    PdfEngine,
    RekorTransparencyLog,
    Rfc3161Timestamper,
    Timestamper,
    TransparencyLog,
    build_evidence_pack,
    control_mappings,
    rekor_keyring,
    render_audit_pack_and_hash,
    to_in_toto_statement,
    verify_pack,
)
from sectum.jobs import build_job_runner
from sectum.probes import (
    AgentFrameworkHijackProbe,
    AgentToolHijackProbe,
    DetectionProviders,
    EmbeddingInversionProbe,
    ErasureProbe,
    IkeaExtractionProbe,
    KvCacheTimingProbe,
    LoraCrossTenantProbe,
    MemoryContamProbe,
    Probe,
    RagEntityBleedProbe,
    RagPipelineBleedProbe,
    RagPoisoningProbe,
    SemanticCacheProbe,
    TenantBoundaryProbe,
    confirmed_findings,
    dedupe_findings,
)
from sectum.runner import Runner, StepResult, retrieval_pivot_rate
from sectum.spec import (
    ConfigError,
    EvidenceError,
    EvidencePack,
    Finding,
    MarkerType,
    RunMetrics,
    RunResult,
    SectumError,
    Substrate,
    canonical_hash,
)
from sectum.substrate import build_substrate, default_scenario
from sectum.sweep import embedding_model_sweep

__version__ = "0.0.0"

_DEFAULT_WORKDIR = Path(".sectum")
_DEFAULT_CONFIG = Path("sectum.yaml")


class OutputFormat(StrEnum):
    """Output rendering for commands that report run-level results to stdout.

    `text` is the default human-readable rendering. `json` emits a single
    machine-parseable JSON object so CI pipelines and scripts can read the
    summary off stdout without scraping prose. Error messages stay on stderr
    in either mode, and exit codes are unchanged.
    """

    TEXT = "text"
    JSON = "json"


def _build_suite(providers: DetectionProviders) -> tuple[Probe, ...]:
    """Construct the probe suite, threading the configured detection providers."""
    return (
        TenantBoundaryProbe(providers),
        RagEntityBleedProbe(providers),
        RagPipelineBleedProbe(providers),
        SemanticCacheProbe(providers),
        LoraCrossTenantProbe(providers),
        AgentToolHijackProbe(providers),
        AgentFrameworkHijackProbe(providers),
        MemoryContamProbe(providers),
        EmbeddingInversionProbe(providers),
        IkeaExtractionProbe(providers),
        RagPoisoningProbe(providers),
    )


# The CLI's default for `sectum probe`: every fake's leak knob is on, so the
# probe suite reproduces the cross-tenant findings the probes are built to
# catch. Override by passing `--config sectum.yaml`.
_DEMO_CONFIG = SectumConfig(
    adapters={
        "vector_store": AdapterConfig(kind="fake", shared_index=True),
        "cache": AdapterConfig(kind="fake", tenant_scoped=False),
        "model": AdapterConfig(kind="fake", adapter_bleed=True, prefix_cache=True),
        "mcp": AdapterConfig(kind="fake", confused_deputy=True, token_passthrough=True),
        "memory": AdapterConfig(kind="fake", shared_memory=True),
        "rag": AdapterConfig(kind="fake", shared_index=True),
        "observability": AdapterConfig(kind="fake"),
        "agent": AdapterConfig(kind="fake", confused_deputy=True, tool_call_passthrough=True),
    }
)

_CONFIG_TEMPLATE = """\
# Sectum AI configuration - see https://docs.sectum.ai
# Generated by `sectum init`. Edit it to point Sectum AI at the stack to verify.

# How the synthetic tenants and their corpora are generated.
scenario:
  seed: 2026
  corpus_profile: demo

# Where run artifacts are written (substrate, run, evidence pack, audit pack).
workdir: .sectum

# Adapters connecting Sectum AI to the stack under test. The defaults are the
# in-memory fakes with their leak knobs turned on - so `sectum probe` reproduces
# the cross-tenant findings the probes are built to catch. Turn the knobs off
# (or point at a live backend) to verify a tenant-isolated stack. Never inline
# credentials - reference them from the environment.
adapters:
  vector_store:
    kind: fake               # fake | pgvector | chroma | weaviate
    shared_index: true       # demo leak: one index serves every tenant
    # dsn_env: SECTUM_PGVECTOR_DSN
  cache:
    kind: fake               # fake | redis
    tenant_scoped: false     # demo leak: a shared key space across tenants
  model:
    kind: fake
    adapter_bleed: true      # demo leak: one tenant's adapter influences others
    prefix_cache: true       # demo leak: a shared KV prefix cache leaks via timing
  mcp:
    kind: fake               # fake | stdio
    confused_deputy: true    # demo leak: the MCP server lost tenant scope
    token_passthrough: true  # demo leak: the server trusts a caller-supplied token
  memory:
    kind: fake
    shared_memory: true      # demo leak: long-term memory crosses tenants
  rag:
    kind: fake               # fake | http
    # url: http://localhost:8080/rag
  observability:
    kind: fake               # fake | phoenix
    # base_url: http://localhost:6007  # compose.yaml publishes Phoenix on 6007
  agent:
    kind: fake               # fake | http
    # url: http://localhost:8080/agent

# Evidence-chain anchoring. The local timestamper is the development default;
# production configures an RFC 3161 TSA and, optionally, a Sigstore Rekor log.
evidence:
  timestamper: local    # local | rfc3161
  # tsa_url: https://freetsa.org/tsr
  rekor: false          # true: also record the run digest in a Sigstore Rekor log
  # rekor_url: https://rekor.sigstore.dev

# At-rest protection for the seeded substrate (which holds the ground-truth
# manifest). Set manifest_key_env to the name of an environment variable holding
# a base64-encoded 32-byte key; `sectum seed` then seals the substrate on disk.
# Generate a key: python -c "import os,base64;print(base64.b64encode(os.urandom(32)).decode())"
security:
  # manifest_key_env: SECTUM_MANIFEST_KEY

# Detection-pipeline providers. The defaults are deterministic offline fakes.
# Configure a real embedding model and judge to run production detection; API
# keys are referenced from the environment, never inlined.
detection:
  embedder:
    kind: fake             # fake | openai
    # model: text-embedding-3-small
    # api_key_env: OPENAI_API_KEY
  judge:
    kind: fake             # fake | openai | anthropic
    # model: gpt-4o-mini
    # api_key_env: OPENAI_API_KEY
  semantic_threshold: 0.62  # raise once a real embedding model is configured
"""

app = typer.Typer(
    name="sectum",
    help="Sectum AI - multi-tenant AI verification.",
    no_args_is_help=True,
    add_completion=False,
)

# The Class-2 probes whose steps feed the headline Retrieval-Pivot Rate: the
# vector-store entity-bleed and the RAG-pipeline-end bleed. Counting only the
# former understates the rate when a leak manifests solely at the pipeline
# surface (it would read 0%).
BLEED_PROBE_IDS = frozenset({RagEntityBleedProbe.id, RagPipelineBleedProbe.id})


def _handle_typed_errors[**P, R](func: Callable[P, R]) -> Callable[P, R]:
    """Translate a ``SectumError`` raised inside a command into the section-10 exit code.

    An ``EvidenceError`` exits with code 4 (evidence verification failure); any
    other ``SectumError`` exits with code 3 (config/adapter error). Other
    exceptions propagate unchanged.
    """

    @functools.wraps(func)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
        try:
            return func(*args, **kwargs)
        except EvidenceError as error:
            typer.echo(f"{type(error).__name__}: {error}", err=True)
            raise typer.Exit(code=4) from error
        except SectumError as error:
            typer.echo(f"{type(error).__name__}: {error}", err=True)
            raise typer.Exit(code=3) from error

    return wrapper


def _version_callback(value: bool) -> None:
    """Print the CLI version and exit when ``--version`` is passed."""
    if value:
        typer.echo(f"sectum {__version__}")
        raise typer.Exit


@app.callback()
def main(
    version: Annotated[
        bool,
        typer.Option(
            "--version",
            help="Show the Sectum AI CLI version and exit.",
            callback=_version_callback,
            is_eager=True,
        ),
    ] = False,
) -> None:
    """Sectum AI - multi-tenant AI verification."""


@app.command(name="adapters")
def list_adapters() -> None:
    """List the installed adapters and their capabilities."""
    registry = AdapterRegistry()
    for fake in (
        FakeVectorStore(),
        FakeRAGPipeline(),
        FakeObservability(),
        FakeAgent(),
        FakeMCP(),
        FakeCache(),
        FakeModel(),
        FakeMemory(),
    ):
        registry.register(fake)
    typer.echo(f"{'ADAPTER':<22}{'FAMILY':<18}CAPABILITIES")
    for adapter in registry.all():
        capabilities = ", ".join(sorted(c.value for c in adapter.capabilities)) or "(none)"
        typer.echo(f"{adapter.name:<22}{adapter.family.value:<18}{capabilities}")


def _resolve_manifest_key(security: SecurityConfig) -> bytes | None:
    """Return the configured at-rest key, or ``None`` when encryption is off."""
    if security.manifest_key_env is None:
        return None
    return load_key_from_env(security.manifest_key_env)


def _write_substrate(substrate: Substrate, workdir: Path, key: bytes | None) -> Path:
    """Persist the substrate to ``workdir``, sealed when a key is given.

    Removes the other variant so a re-seed never leaves a stale copy behind - in
    particular, a plaintext substrate must not survive once a sealed one is
    written, or the at-rest protection would be silently defeated.
    """
    payload = substrate.model_dump_json(indent=2).encode("utf-8")
    sealed_path = workdir / "substrate.json.enc"
    plain_path = workdir / "substrate.json"
    if key is not None:
        sealed_path.write_bytes(seal_bytes(payload, key))
        plain_path.unlink(missing_ok=True)
        return sealed_path
    plain_path.write_bytes(payload)
    sealed_path.unlink(missing_ok=True)
    return plain_path


def _load_substrate(workdir: Path, key: bytes | None = None) -> Substrate:
    """Load the seeded substrate from ``workdir``, or exit with a config error.

    A sealed substrate (``substrate.json.enc``) requires the matching key; a
    plaintext ``substrate.json`` is loaded directly.
    """
    sealed = workdir / "substrate.json.enc"
    plain = workdir / "substrate.json"
    if sealed.exists():
        if key is None:
            typer.echo(
                f"the substrate at {sealed} is encrypted; set security.manifest_key_env",
                err=True,
            )
            raise typer.Exit(code=3)
        try:
            return Substrate.model_validate_json(unseal_bytes(sealed.read_bytes(), key))
        except ValueError as error:
            typer.echo(f"the substrate at {sealed} is malformed: {error}", err=True)
            raise typer.Exit(code=3) from error
    if plain.exists():
        try:
            return Substrate.model_validate_json(plain.read_text())
        except ValueError as error:
            typer.echo(f"the substrate at {plain} is malformed: {error}", err=True)
            raise typer.Exit(code=3) from error
    typer.echo(f"no substrate at {plain}; run 'sectum seed' first", err=True)
    raise typer.Exit(code=3)


def _load_run(workdir: Path) -> RunResult:
    """Load the recorded run from ``workdir``, or exit with a config error."""
    path = workdir / "run.json"
    if not path.exists():
        typer.echo(f"no run at {path}; run 'sectum probe' first", err=True)
        raise typer.Exit(code=3)
    try:
        return RunResult.model_validate_json(path.read_text())
    except ValueError as error:
        typer.echo(f"the run at {path} is malformed: {error}", err=True)
        raise typer.Exit(code=3) from error


def _per_probe_counts(findings: list[Finding]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for finding in findings:
        counts[finding.probe_id] = counts.get(finding.probe_id, 0) + 1
    return counts


def _resolve_target(substrate: Substrate, name: str | None) -> UUID:
    """Resolve a target tenant by display name, defaulting to the first tenant."""
    if name is None:
        return substrate.tenants[0].tenant_id
    for tenant in substrate.tenants:
        if tenant.display_name.lower() == name.lower():
            return tenant.tenant_id
    available = ", ".join(tenant.display_name for tenant in substrate.tenants)
    typer.echo(f"unknown tenant '{name}'; available: {available}", err=True)
    raise typer.Exit(code=3)


@app.command()
@_handle_typed_errors
def seed(
    scenario_seed: Annotated[int | None, typer.Option("--seed", help="Scenario seed.")] = None,
    workdir: Annotated[Path | None, typer.Option(help="Directory for run artifacts.")] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Provision synthetic tenants, generate corpora, and plant canary markers."""
    loaded = load_config(config) if config is not None else SectumConfig()
    effective_seed = scenario_seed if scenario_seed is not None else loaded.scenario.seed
    effective_workdir = workdir if workdir is not None else loaded.workdir
    substrate = build_substrate(default_scenario(seed=effective_seed))
    effective_workdir.mkdir(parents=True, exist_ok=True)
    path = _write_substrate(substrate, effective_workdir, _resolve_manifest_key(loaded.security))
    typer.echo(
        f"seeded {len(substrate.tenants)} tenants and "
        f"{len(substrate.documents)} documents -> {path}"
    )


@app.command()
@_handle_typed_errors
def probe(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the seeded substrate.")
    ] = None,
    only: Annotated[
        str | None, typer.Option("--probe", help="Run only the probe with this id.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read adapters and workdir from this sectum.yaml file."),
    ] = None,
    max_concurrency: Annotated[
        int,
        typer.Option(
            "--max-concurrency",
            help=(
                "Run probes in parallel via a thread pool (1 = serial). N > 1 requires "
                "thread-safe adapters AND that probe order does not matter; the demo's "
                "in-memory fakes share state across mutating and reading probes, so "
                "concurrent execution there yields nondeterministic findings."
            ),
        ),
    ] = 1,
    output: Annotated[
        OutputFormat,
        typer.Option(
            "--output",
            help=(
                "Render the run summary on stdout. `text` is human-readable (default); "
                "`json` emits a single machine-parseable object for CI pipelines."
            ),
            case_sensitive=False,
        ),
    ] = OutputFormat.TEXT,
) -> None:
    """Run the probe suite against the configured stack and record the findings."""
    if max_concurrency < 1:
        raise ConfigError("--max-concurrency must be at least 1")
    loaded = load_config(config) if config is not None else _DEMO_CONFIG
    effective_workdir = workdir if workdir is not None else loaded.workdir
    substrate = _load_substrate(effective_workdir, _resolve_manifest_key(loaded.security))
    suite = _build_suite(build_detection_providers(loaded.detection))
    run_kv_timing = True
    if only is not None:
        available = [instance.id for instance in suite] + [KvCacheTimingProbe.id]
        if only not in available:
            typer.echo(f"unknown probe '{only}'; available: {', '.join(available)}", err=True)
            raise typer.Exit(code=3)
        suite = tuple(instance for instance in suite if instance.id == only)
        run_kv_timing = only == KvCacheTimingProbe.id
    bundle = build_adapters(loaded)
    vector = bundle.vector
    cache = bundle.cache
    model = bundle.model
    mcp = bundle.mcp
    memory = bundle.memory
    for tenant in substrate.tenants:
        documents = [doc for doc in substrate.documents if doc.tenant_id == tenant.tenant_id]
        vector.upsert(tenant.tenant_id, documents)
    if isinstance(mcp, FakeMCP):
        for marker in substrate.manifest.markers:
            if marker.marker_type is MarkerType.HARD_CANARY:
                mcp.provision(
                    marker.owner_tenant_id,
                    marker.marker_id,
                    f"MCP resource. Reference: {marker.plaintext}",
                )
    if isinstance(bundle.agent, FakeAgent):
        for marker in substrate.manifest.markers:
            if marker.marker_type is MarkerType.HARD_CANARY:
                bundle.agent.provision(
                    marker.owner_tenant_id,
                    marker.marker_id,
                    f"agent tool returned. Reference: {marker.plaintext}",
                )
    if isinstance(bundle.rag, FakeRAGPipeline):
        for tenant in substrate.tenants:
            documents = [doc for doc in substrate.documents if doc.tenant_id == tenant.tenant_id]
            bundle.rag.index(tenant.tenant_id, documents)
    runner = Runner(
        substrate,
        vector=vector,
        cache=cache,
        model=model,
        mcp=mcp,
        memory=memory,
        rag=bundle.rag,
        observability=bundle.observability,
        agent=bundle.agent,
    )

    started = datetime.now(UTC)
    step_results: list[StepResult] = []
    # A single probe stays serial regardless of --max-concurrency (a pool is only
    # worth its overhead for a suite > 1). The JobRunner is the seam where a
    # distributed orchestrator could later replace local threads (spec section 21).
    job_runner = build_job_runner(max_concurrency if len(suite) > 1 else 1)
    for group in job_runner.map(runner.run_per_step, suite):
        step_results.extend(group)
    kv_report = KvCacheTimingProbe(substrate, model=model).run() if run_kv_timing else None
    finished = datetime.now(UTC)

    suite_findings = [finding for _, group in step_results for finding in group]
    kv_findings = list(kv_report.findings) if kv_report is not None else []
    findings = tuple(dedupe_findings([*suite_findings, *kv_findings]))
    confirmed = confirmed_findings(findings)
    bleed_steps = [result for result in step_results if result[0].probe_id in BLEED_PROBE_IDS]
    run = RunResult(
        run_id=f"run-{substrate.scenario.scenario_id}",
        scenario_hash=canonical_hash(substrate.scenario),
        manifest_hash=canonical_hash(substrate.manifest),
        started_at=started,
        finished_at=finished,
        adapter_versions={
            vector.name: __version__,
            cache.name: __version__,
            model.name: __version__,
            mcp.name: __version__,
            memory.name: __version__,
            bundle.rag.name: __version__,
            bundle.observability.name: __version__,
            bundle.agent.name: __version__,
        },
        probe_versions={
            **{instance.id: __version__ for instance in suite},
            **({KvCacheTimingProbe.id: __version__} if run_kv_timing else {}),
        },
        findings=findings,
        metrics=RunMetrics(
            confirmed_findings=len(confirmed),
            retrieval_pivot_rate=retrieval_pivot_rate(bleed_steps) if bleed_steps else None,
            # The sweep is a fake-substrate illustration of the embedding-strength
            # effect, so it is recorded only for in-memory-store runs - a live
            # vector adapter's evidence carries no fake-derived per-model rates.
            retrieval_pivot_rate_by_model=(
                embedding_model_sweep(substrate, substrate.scenario.embedding_models)
                if isinstance(vector, FakeVectorStore)
                and len(substrate.scenario.embedding_models) > 1
                else {}
            ),
            per_probe_findings=_per_probe_counts(confirmed),
            side_channel_effect_sizes=kv_report.effect_sizes if kv_report is not None else {},
        ),
    )
    path = effective_workdir / "run.json"
    path.write_text(run.model_dump_json(indent=2))
    probe_count = len(suite) + (1 if run_kv_timing else 0)
    if output is OutputFormat.JSON:
        # Single-shot JSON object so the consumer can `jq .` it. The full run
        # is still on disk at `run_path`; this is the summary CI dashboards read.
        summary = {
            "run_id": run.run_id,
            "probe_count": probe_count,
            "confirmed_findings": len(confirmed),
            "retrieval_pivot_rate": run.metrics.retrieval_pivot_rate,
            "retrieval_pivot_rate_by_model": run.metrics.retrieval_pivot_rate_by_model,
            "per_probe_findings": run.metrics.per_probe_findings,
            "run_path": str(path),
        }
        typer.echo(json.dumps(summary, indent=2))
    else:
        plural = "" if probe_count == 1 else "s"
        typer.echo(
            f"ran {probe_count} probe{plural}: {len(confirmed)} confirmed cross-tenant findings"
        )
        if run.metrics.retrieval_pivot_rate is not None:
            typer.echo(f"retrieval-pivot rate: {run.metrics.retrieval_pivot_rate:.0%}")
        for model_name, rate in run.metrics.retrieval_pivot_rate_by_model.items():
            typer.echo(f"  retrieval-pivot rate [{model_name}]: {rate:.0%}")
        typer.echo(f"run recorded -> {path}")
    if confirmed:
        raise typer.Exit(code=2)


def _resolve_timestamper(evidence: EvidenceConfig, tsa_override: str | None) -> Timestamper | None:
    """Resolve the configured timestamper, or ``None`` to use the local default.

    A ``--tsa <url>`` override forces an RFC 3161 TSA; otherwise the
    ``evidence.timestamper`` setting selects ``local`` (default) or ``rfc3161``.
    """
    if tsa_override is not None:
        return Rfc3161Timestamper(tsa_override)
    if evidence.timestamper == "rfc3161":
        url = evidence.tsa_url
        return Rfc3161Timestamper(url) if url is not None else Rfc3161Timestamper()
    return None


def _resolve_transparency_log(evidence: EvidenceConfig, rekor_flag: bool) -> TransparencyLog | None:
    """Resolve a Rekor transparency log when enabled by ``--rekor`` or the config.

    Recording uses an ephemeral signing key; the transparency guarantee is the
    public, timestamped inclusion of the digest, not the signer's identity.
    """
    if not (rekor_flag or evidence.rekor):
        return None
    url = evidence.rekor_url
    return RekorTransparencyLog(rekor_url=url) if url is not None else RekorTransparencyLog()


def _rekor_keyring_override(rekor_key: Path | None) -> dict[str, bytes] | None:
    """Build a one-key Rekor keyring from a ``--rekor-key`` PEM file, or ``None``."""
    if rekor_key is None:
        return None
    return rekor_keyring(rekor_key.read_bytes())


@app.command()
@_handle_typed_errors
def report(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the substrate and run.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
    tsa: Annotated[
        str | None,
        typer.Option("--tsa", help="RFC 3161 TSA URL; switches the timestamper to a trusted TSA."),
    ] = None,
    rekor: Annotated[
        bool,
        typer.Option("--rekor", help="Also record the run digest in a Sigstore Rekor log."),
    ] = False,
    pdf_engine: Annotated[
        PdfEngine,
        typer.Option(
            "--pdf-engine",
            help=(
                "Audit-pack PDF renderer. 'reportlab' (default) is pure Python; "
                "'weasyprint' is an HTML/CSS-templated alternative and needs the "
                "weasyprint extra (pip install 'sectum-ai[weasyprint]')."
            ),
            case_sensitive=False,
        ),
    ] = PdfEngine.REPORTLAB,
) -> None:
    """Assemble a tamper-evident evidence pack (JSON and PDF) from the run."""
    loaded = load_config(config) if config is not None else SectumConfig()
    if workdir is None:
        workdir = loaded.workdir
    substrate = _load_substrate(workdir, _resolve_manifest_key(loaded.security))
    run = _load_run(workdir)
    timestamper = _resolve_timestamper(loaded.evidence, tsa)
    transparency_log = _resolve_transparency_log(loaded.evidence, rekor)
    controls = control_mappings()
    # Render the audit PDF first and bind its hash as pdf_ref so the signed
    # attested digest covers the PDF; the PDF renders only digest-stable content,
    # so the on-disk file re-hashes to this pdf_ref and `sectum verify` catches a
    # swap.
    pdf_path = workdir / "audit-pack.pdf"
    pdf_ref = render_audit_pack_and_hash(
        run, canonical_hash(substrate.manifest), controls, pdf_path, engine=pdf_engine
    )
    pack = build_evidence_pack(
        run,
        substrate.manifest,
        control_mappings=controls,
        pdf_ref=pdf_ref,
        timestamper=timestamper,
        transparency_log=transparency_log,
    )
    json_path = workdir / "evidence.json"
    json_path.write_text(pack.model_dump_json(indent=2))
    intoto_path = workdir / "attestation.intoto.json"
    intoto_path.write_text(json.dumps(to_in_toto_statement(pack), indent=2))
    typer.echo(f"evidence pack -> {json_path}")
    typer.echo(f"audit pack -> {pdf_path}")
    typer.echo(f"in-toto attestation -> {intoto_path}")


def _sibling_audit_pdf(pack_path: Path) -> bytes | None:
    """Return the bytes of the audit PDF written beside ``pack_path``, if present.

    The ``report`` and ``erasure`` commands write the audit PDF next to the
    evidence json (``audit-pack.pdf`` / ``erasure-attestation.pdf``). When one is
    present, ``sectum verify`` re-hashes it against the pack's bound ``pdf_ref``;
    when absent, verification still proceeds from the json alone.
    """
    for name in ("audit-pack.pdf", "erasure-attestation.pdf"):
        candidate = pack_path.parent / name
        if candidate.exists():
            return candidate.read_bytes()
    return None


@app.command()
def verify(
    pack: Annotated[Path, typer.Argument(help="Path to an evidence.json pack.")],
    tsa_cert: Annotated[
        Path | None,
        typer.Option("--tsa-cert", help="PEM of the TSA leaf certificate (overrides FreeTSA)."),
    ] = None,
    tsa_root: Annotated[
        Path | None,
        typer.Option("--tsa-root", help="PEM of the TSA root certificate (overrides FreeTSA)."),
    ] = None,
    rekor_key: Annotated[
        Path | None,
        typer.Option("--rekor-key", help="PEM of a Rekor public key (pins a private instance)."),
    ] = None,
) -> None:
    """Independently verify a tamper-evident evidence pack."""
    if not pack.exists():
        typer.echo(f"no evidence pack at {pack}", err=True)
        raise typer.Exit(code=3)
    for label, cert_path in (
        ("--tsa-cert", tsa_cert),
        ("--tsa-root", tsa_root),
        ("--rekor-key", rekor_key),
    ):
        if cert_path is not None and not cert_path.exists():
            typer.echo(f"no certificate at {cert_path} for {label}", err=True)
            raise typer.Exit(code=3)
    try:
        # pydantic's ValidationError is a ValueError; this also catches invalid JSON.
        evidence = EvidencePack.model_validate_json(pack.read_text())
    except ValueError as error:
        typer.echo(f"not a valid evidence pack at {pack}: {error}", err=True)
        raise typer.Exit(code=3) from error
    # Re-hash the audit PDF if it sits beside the pack (report/erasure write
    # audit-pack.pdf / erasure-attestation.pdf next to the json); its hash is
    # bound into the attested digest, so a swapped PDF fails verification.
    pdf_bytes = _sibling_audit_pdf(pack)
    result = verify_pack(
        evidence,
        tsa_certificate=tsa_cert.read_bytes() if tsa_cert is not None else None,
        tsa_root=tsa_root.read_bytes() if tsa_root is not None else None,
        rekor_keyring=_rekor_keyring_override(rekor_key),
        pdf_bytes=pdf_bytes,
    )
    for check in result.checks:
        typer.echo(f"[{'ok' if check.ok else 'FAIL'}] {check.name}: {check.detail}")
    if not result.passed:
        typer.echo("VERIFICATION FAILED", err=True)
        raise typer.Exit(code=4)
    typer.echo("VERIFIED: the evidence pack's attested content is intact and consistent.")
    typer.echo(
        "note: this confirms integrity and internal consistency; to also bind which "
        "marker belonged to which tenant, re-run with the original ground-truth manifest.",
        err=True,
    )


@app.command()
@_handle_typed_errors
def erasure(
    target_tenant: Annotated[
        str | None, typer.Option("--target-tenant", help="Tenant display name.")
    ] = None,
    soft_delete: Annotated[
        bool,
        typer.Option(
            "--soft-delete",
            help=(
                "Model a store that fails erasure. Ignored when --config is given; "
                "set 'soft_delete: true' on the adapter in the config instead."
            ),
        ),
    ] = False,
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the seeded substrate.")
    ] = None,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Run the GDPR Article 17 erasure-verification workflow (Class 11, the wedge)."""
    if config is not None:
        loaded = load_config(config)
        fake_default = AdapterConfig(kind="fake")
        if soft_delete:
            typer.echo(
                "warning: --soft-delete is ignored when --config is given; "
                "set 'soft_delete: true' on the adapter in the config instead.",
                err=True,
            )
    else:
        loaded = SectumConfig()
        fake_default = AdapterConfig(kind="fake", soft_delete=soft_delete)
    if workdir is None:
        workdir = loaded.workdir
    substrate = _load_substrate(workdir, _resolve_manifest_key(loaded.security))
    target = _resolve_target(substrate, target_tenant)
    store = build_vector_store(loaded.adapters.get("vector_store", fake_default))
    obs = build_observability(loaded.adapters.get("observability", fake_default))
    memory = build_memory(loaded.adapters.get("memory", fake_default))
    cache = build_cache(loaded.adapters.get("cache", fake_default))
    model = build_model(loaded.adapters.get("model", fake_default))
    # The search index and eval set have no live adapters yet; deterministic
    # fakes model them. soft_delete rides on fake_default's extras (set from
    # --soft-delete when no config is given, absent under --config).
    _fake_soft_delete = bool((fake_default.model_extra or {}).get("soft_delete"))
    search = FakeSearchIndex(soft_delete=_fake_soft_delete)
    evalset = FakeEvalSet(soft_delete=_fake_soft_delete)
    for tenant in substrate.tenants:
        documents = [doc for doc in substrate.documents if doc.tenant_id == tenant.tenant_id]
        store.upsert(tenant.tenant_id, documents)
    for marker in substrate.manifest.markers:
        if marker.marker_type is not MarkerType.HARD_CANARY:
            continue
        if isinstance(obs, FakeObservability):
            obs.record(
                marker.owner_tenant_id,
                "sectum-erasure",
                f"trace recording marker {marker.plaintext}",
            )
        if isinstance(memory, FakeMemory):
            memory.remember(marker.owner_tenant_id, f"memory note recording {marker.plaintext}")
        if isinstance(cache, FakeCache):
            cache.set(
                marker.owner_tenant_id,
                f"sectum-erasure-{marker.marker_id}",
                f"cached answer mentioning {marker.plaintext}",
            )
        if isinstance(model, FakeModel):
            model.train_adapter(marker.owner_tenant_id, [f"fine-tune sample {marker.plaintext}"])
        search.index(marker.owner_tenant_id, f"search index entry mentioning {marker.plaintext}")
        evalset.add(marker.owner_tenant_id, f"eval set fixture mentioning {marker.plaintext}")

    started = datetime.now(UTC)
    report = ErasureProbe(
        substrate,
        vector=store,
        observability=obs,
        memory=memory,
        cache=cache,
        model=model,
        search_index=search,
        eval_set=evalset,
    ).run(target)
    finished = datetime.now(UTC)

    run = RunResult(
        run_id=f"erasure-{target.hex[:8]}",
        scenario_hash=canonical_hash(substrate.scenario),
        manifest_hash=canonical_hash(substrate.manifest),
        started_at=started,
        finished_at=finished,
        adapter_versions={
            store.name: __version__,
            obs.name: __version__,
            memory.name: __version__,
            cache.name: __version__,
            model.name: __version__,
            search.name: __version__,
            evalset.name: __version__,
        },
        probe_versions={ErasureProbe.id: __version__},
        findings=report.findings,
        metrics=RunMetrics(
            # Count only genuinely confirmed findings (residual-after-erasure),
            # not the whole list: attestable-with-caveat findings are UNVERIFIED
            # (a same-tenant backend limitation, not a confirmed leak), so
            # counting len(report.findings) would inflate the headline count and
            # make `sectum diff`/`baseline` read a no-per-tenant-erasure-API
            # backend as a regression. confirmed_findings() filters to confirmed.
            confirmed_findings=len(confirmed_findings(report.findings)),
            # Genuine residual (a surface that supports erasure but still holds
            # the marker) is kept separate from caveat surfaces (no per-tenant
            # erasure API) so the signed pack and the baseline diff never
            # conflate a backend limitation with an erasure failure.
            erasure_residue={
                surface.surface.value: surface.residual_after
                for surface in report.surfaces
                if surface.erasure_supported
            },
            erasure_caveats={
                surface.surface.value: surface.residual_after
                for surface in report.surfaces
                if not surface.erasure_supported
            },
        ),
    )
    controls = control_mappings()
    # Bind the audit PDF into the attested digest (see `report`).
    pdf_path = workdir / "erasure-attestation.pdf"
    pdf_ref = render_audit_pack_and_hash(
        run, canonical_hash(substrate.manifest), controls, pdf_path
    )
    pack = build_evidence_pack(
        run,
        substrate.manifest,
        control_mappings=controls,
        pdf_ref=pdf_ref,
        timestamper=_resolve_timestamper(loaded.evidence, None),
        transparency_log=_resolve_transparency_log(loaded.evidence, False),
    )
    json_path = workdir / "erasure-evidence.json"
    json_path.write_text(pack.model_dump_json(indent=2))
    intoto_path = workdir / "erasure-attestation.intoto.json"
    intoto_path.write_text(json.dumps(to_in_toto_statement(pack), indent=2))

    for surface in report.surfaces:
        typer.echo(
            f"{surface.surface.value}: {surface.markers_before} markers before, "
            f"{surface.residual_after} after -> {surface.verdict}"
        )
    typer.echo(f"erasure attestation -> {json_path}, {pdf_path}")
    # A genuine erasure failure (a surface that supports erasure but still
    # holds the marker) is the dominant signal and takes precedence.
    if report.genuine_residual:
        typer.echo("ERASURE FAILED: residual data remains.", err=True)
        # A caveat surface can co-exist with a genuine failure; itemize it too
        # rather than letting the dominant failure hide it - the data on a
        # no-erasure-API backend is still presumed retained.
        if report.caveats:
            caveat_names = ", ".join(surface.surface.value for surface in report.caveats)
            typer.echo(
                f"  also attestable-with-caveat: {caveat_names} expose no per-tenant "
                "erasure API, so that data is presumed retained (a backend "
                "limitation, itemized in the attestation).",
                err=True,
            )
        raise typer.Exit(code=2)
    # A caveat surface (no programmatic per-tenant erasure API) holds data that
    # is presumed retained - never a clean PASS, but a documented backend
    # limitation rather than a flow failure. Exit non-zero (the data is still
    # there) but say so distinctly so a DPO does not read it as an isolation
    # defect (spec §7, Class 11, hiding place #8).
    if report.caveats:
        names = ", ".join(surface.surface.value for surface in report.caveats)
        typer.echo(
            f"ERASURE ATTESTABLE WITH CAVEAT: {names} expose no per-tenant erasure "
            "API, so the tenant's data is presumed retained until it ages out of "
            "the backend's retention window. Itemized as a caveat in the "
            "attestation - a backend limitation, not a failure of the erasure flow.",
            err=True,
        )
        raise typer.Exit(code=2)
    if report.erased:
        scanned = ", ".join(surface.surface.value for surface in report.surfaces)
        typer.echo(f"ERASURE VERIFIED: no residual marker on {scanned}.")
        return
    no_baseline = [
        surface.surface.value for surface in report.surfaces if surface.markers_before == 0
    ]
    typer.echo(
        f"ERASURE INCONCLUSIVE: no baseline on {', '.join(no_baseline)} - "
        "the target tenant's markers were not found on those surfaces, so "
        "erasure cannot be attested.",
        err=True,
    )
    raise typer.Exit(code=3)


@app.command()
def init(
    output: Annotated[
        Path, typer.Option(help="Path for the generated config file.")
    ] = _DEFAULT_CONFIG,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite an existing config file.")
    ] = False,
) -> None:
    """Scaffold a sectum.yaml configuration file."""
    if output.exists() and not force:
        typer.echo(f"{output} already exists; pass --force to overwrite", err=True)
        raise typer.Exit(code=3)
    output.write_text(_CONFIG_TEMPLATE)
    typer.echo(f"wrote {output}")


def _delta_verdict(delta: MetricDelta) -> str:
    """The status tag for a metric delta line: regression, informational, or ok."""
    if delta.informational:
        return "info"
    return "REGRESSED" if delta.regressed else "ok"


@app.command()
def baseline(
    workdir: Annotated[
        Path | None, typer.Option(help="Directory holding the recorded run.")
    ] = None,
    save: Annotated[
        bool, typer.Option("--save", help="Save the current run as the baseline.")
    ] = False,
    compare: Annotated[
        bool,
        typer.Option("--compare", help="Compare the current run against the saved baseline."),
    ] = False,
    config: Annotated[
        Path | None,
        typer.Option("--config", help="Read defaults from this sectum.yaml file."),
    ] = None,
) -> None:
    """Save a regression baseline from the current run, or compare against it."""
    loaded = load_config(config) if config is not None else SectumConfig()
    if workdir is None:
        workdir = loaded.workdir
    run = _load_run(workdir)
    baseline_path = workdir / "baseline.json"
    if save:
        baseline_path.write_text(run.model_dump_json(indent=2))
        typer.echo(f"baseline saved -> {baseline_path}")
        return
    if not compare:
        typer.echo("pass --save to record a baseline or --compare to check against it", err=True)
        raise typer.Exit(code=3)
    if not baseline_path.exists():
        typer.echo(f"no baseline at {baseline_path}; run 'sectum baseline --save' first", err=True)
        raise typer.Exit(code=3)
    try:
        saved = RunResult.model_validate_json(baseline_path.read_text())
    except ValueError as error:
        typer.echo(
            f"the baseline at {baseline_path} is malformed "
            f"(re-run 'sectum baseline --save' to refresh it): {error}",
            err=True,
        )
        raise typer.Exit(code=3) from error
    # Use the full run diff (the same logic as `sectum diff`), not a metric-only
    # comparison: a leak that newly confirmed or escalated in severity is a
    # regression the headline counts can miss.
    result = diff_runs(saved, run)
    for delta in result.metrics.deltas:
        typer.echo(
            f"[{_delta_verdict(delta)}] {delta.name}: {delta.baseline:g} -> {delta.current:g}"
        )
    for change in result.findings.severity_escalations:
        typer.echo(
            f"[REGRESSED] severity escalated: {change.previous.finding_id} "
            f"{change.previous.severity.value} -> {change.current.severity.value}"
        )
    for finding in result.findings.newly_confirmed:
        typer.echo(f"[REGRESSED] newly confirmed leak: {finding.finding_id}")
    if result.regressed:
        typer.echo(
            "BASELINE REGRESSION: a metric worsened, a leak was newly confirmed, "
            "or a confirmed leak escalated in severity.",
            err=True,
        )
        raise typer.Exit(code=2)
    typer.echo("no regression against the baseline")


def _load_run_artifact(path: Path) -> RunResult:
    """Load a :class:`RunResult` from a ``run.json`` or an evidence pack of one.

    Accepts either the run record written by ``sectum probe`` or an
    ``evidence.json`` pack (whose ``run_result`` is unwrapped), so two signed
    packs compare directly. Raises :class:`ConfigError` for a missing file,
    malformed JSON, or a payload that is neither shape.
    """
    if not path.exists():
        raise ConfigError(f"no such run file: {path}")
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as error:
        raise ConfigError(f"{path} is not valid JSON: {error}") from error
    try:
        if isinstance(data, dict) and "run_result" in data:
            return EvidencePack.model_validate(data).run_result
        return RunResult.model_validate(data)
    except ValidationError as error:
        raise ConfigError(f"{path} is not a sectum run or evidence pack: {error}") from error


def _finding_row(finding: Finding) -> dict[str, str | None]:
    """A JSON-safe, comparison-relevant subset of a finding for diff output.

    The user dimension (ADR-0006) is included when set, so two distinct
    cross-user leaks within one tenant do not collapse to the same row; both
    user fields are ``null`` for a tenant-level finding.
    """
    return {
        "finding_id": finding.finding_id,
        "probe_id": finding.probe_id,
        "severity": finding.severity.value,
        "status": finding.status.value,
        "surface": finding.surface.value,
        "owner_tenant_id": str(finding.owner_tenant_id),
        "observed_in_tenant_id": str(finding.observed_in_tenant_id),
        "owner_user_id": str(finding.owner_user_id) if finding.owner_user_id else None,
        "observed_in_user_id": (
            str(finding.observed_in_user_id) if finding.observed_in_user_id else None
        ),
    }


def _change_row(change: FindingChange) -> dict[str, str | None]:
    """A finding row for an in-place change, carrying its previous status/severity."""
    row = _finding_row(change.current)
    row["previous_status"] = change.previous.status.value
    row["previous_severity"] = change.previous.severity.value
    return row


def _render_diff_text(earlier: Path, later: Path, result: RunDiff) -> None:
    """Print the human-readable diff: finding changes, metric deltas, verdict."""
    findings = result.findings
    typer.echo(f"sectum diff: {earlier} -> {later}")
    typer.echo("")
    typer.echo("Findings:")
    typer.echo(
        f"  + {len(findings.appeared)} appeared, "
        f"- {len(findings.resolved)} resolved, "
        f"= {len(findings.persisting)} persisting, "
        f"! {len(findings.newly_confirmed)} newly confirmed, "
        f"~ {len(findings.changed)} changed"
    )

    def _line(sign: str, finding: Finding) -> str:
        owner = str(finding.owner_tenant_id)[:8]
        observed = str(finding.observed_in_tenant_id)[:8]
        return (
            f"    {sign} [{finding.status.value}/{finding.severity.value}] "
            f"{finding.probe_id}  {owner} -> {observed}  "
            f"({finding.surface.value})  {finding.finding_id[:12]}"
        )

    escalation_ids = {change.current.finding_id for change in findings.severity_escalations}

    def _change_line(change: FindingChange) -> str:
        finding = change.current
        owner = str(finding.owner_tenant_id)[:8]
        observed = str(finding.observed_in_tenant_id)[:8]
        sign = "!" if finding.finding_id in escalation_ids else "~"
        transition = (
            f"{change.previous.status.value}/{change.previous.severity.value}"
            f" -> {finding.status.value}/{finding.severity.value}"
        )
        return (
            f"    {sign} [{transition}] {finding.probe_id}  "
            f"{owner} -> {observed}  ({finding.surface.value})  "
            f"{finding.finding_id[:12]}"
        )

    if findings.appeared:
        typer.echo("  appeared:")
        for finding in findings.appeared:
            typer.echo(_line("+", finding))
    if findings.resolved:
        typer.echo("  resolved:")
        for finding in findings.resolved:
            typer.echo(_line("-", finding))
    if findings.changed:
        typer.echo("  changed:")
        for change in findings.changed:
            typer.echo(_change_line(change))

    typer.echo("")
    typer.echo("Metrics:")
    for delta in result.metrics.deltas:
        typer.echo(
            f"  [{_delta_verdict(delta)}] {delta.name}: {delta.baseline:g} -> {delta.current:g}"
        )

    typer.echo("")
    typer.echo("RESULT: REGRESSION" if result.regressed else "RESULT: no regression")


def _render_diff_json(earlier: Path, later: Path, result: RunDiff) -> None:
    """Print the diff as one machine-parseable JSON object on stdout."""
    payload = {
        "earlier": str(earlier),
        "later": str(later),
        "findings": {
            "appeared": [_finding_row(f) for f in result.findings.appeared],
            "resolved": [_finding_row(f) for f in result.findings.resolved],
            "newly_confirmed": [_finding_row(f) for f in result.findings.newly_confirmed],
            "changed": [_change_row(c) for c in result.findings.changed],
            "severity_escalation_count": len(result.findings.severity_escalations),
            "persisting_count": len(result.findings.persisting),
        },
        "metrics": [
            {
                "name": delta.name,
                "baseline": delta.baseline,
                "current": delta.current,
                "regressed": delta.regressed,
                "informational": delta.informational,
            }
            for delta in result.metrics.deltas
        ],
        "regressed": result.regressed,
    }
    typer.echo(json.dumps(payload, indent=2))


@app.command()
@_handle_typed_errors
def diff(
    earlier: Annotated[
        Path,
        typer.Argument(help="The earlier/reference run.json or evidence.json."),
    ],
    later: Annotated[
        Path,
        typer.Argument(help="The later run.json or evidence.json under scrutiny."),
    ],
    output: Annotated[
        OutputFormat,
        typer.Option(
            "--output",
            help=(
                "Render the diff on stdout. `text` is human-readable (default); "
                "`json` emits a single machine-parseable object for CI pipelines."
            ),
            case_sensitive=False,
        ),
    ] = OutputFormat.TEXT,
) -> None:
    """Diff two runs (or evidence packs): new, resolved, changed, persisting findings.

    Compares metric deltas (as ``baseline --compare`` does) and, in addition, the
    findings themselves keyed by id - including in-place changes (status or
    severity). Exits with code 2 when the later run regressed - any worsened
    metric, a newly confirmed finding, or a severity escalation of a finding
    confirmed in both runs - else 0, so the command can gate a CI pipeline (the
    engineering spec, section 10).
    """
    earlier_run = _load_run_artifact(earlier)
    later_run = _load_run_artifact(later)
    result = diff_runs(earlier_run, later_run)
    if output is OutputFormat.JSON:
        _render_diff_json(earlier, later, result)
    else:
        _render_diff_text(earlier, later, result)
    if result.regressed:
        raise typer.Exit(code=2)


if __name__ == "__main__":  # pragma: no cover
    app()
