"""The Sectum AI probe interface and registry (the engineering spec, section 7).

A probe implements one attack class behind a stable interface, so the catalog
is pluggable. Planning is deterministic from the scenario and seed; detection is
side-effecting only through adapters.
"""

import sys
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

import yaml

from sectum.spec import Finding, Observation, ProbeStep, Substrate, Surface


@runtime_checkable
class Probe(Protocol):
    """A pluggable attack-class probe (the engineering spec, section 7.0)."""

    id: str
    name: str
    owasp_llm: str
    atlas_techniques: tuple[str, ...]
    nist_rmf: tuple[str, ...]
    surfaces: tuple[Surface, ...]
    requires_adapters: tuple[str, ...]

    def plan(self, substrate: Substrate) -> list[ProbeStep]:
        """Deterministically produce the steps (queries or actions) to run.

        Takes the full substrate (ADR-0004) so manifest-grounded probes can plan.
        """
        ...

    def detect(
        self, step: ProbeStep, observation: Observation, substrate: Substrate
    ) -> list[Finding]:
        """Apply the detection pipeline to one observation; return findings."""
        ...


class ProbeRegistry:
    """An in-memory registry of probes, keyed by probe id."""

    def __init__(self) -> None:
        self._probes: dict[str, Probe] = {}

    def register(self, probe: Probe) -> None:
        """Register ``probe`` under its id."""
        if probe.id in self._probes:
            raise ValueError(f"probe already registered: {probe.id}")
        self._probes[probe.id] = probe

    def get(self, probe_id: str) -> Probe:
        """Return the probe registered under ``probe_id``."""
        return self._probes[probe_id]

    def all(self) -> list[Probe]:
        """Return every registered probe, ordered by id."""
        return [self._probes[probe_id] for probe_id in sorted(self._probes)]


def load_probe_manifest(probe: type[Probe] | Probe) -> dict[str, Any]:
    """Load the ``probe.yaml`` manifest shipped beside a probe's module.

    The manifest (the engineering spec, section 7.0) is a declarative mirror of
    the probe's class attributes - id, name, OWASP/ATLAS/NIST mappings, surfaces,
    required adapters, and a runnable example pointer - so the catalog can be
    consumed without importing Python (the suite selector, dashboards, external
    tooling). The class attributes remain authoritative; the manifests are
    regenerated by ``scripts/gen_probe_manifests.py`` and parity is enforced by
    ``tests/unit/test_probe_manifests.py``.
    """
    module_name = probe.__module__ if isinstance(probe, type) else type(probe).__module__
    manifest_path = Path(str(sys.modules[module_name].__file__)).parent / "probe.yaml"
    loaded: dict[str, Any] = yaml.safe_load(manifest_path.read_text())
    return loaded
