"""Sectum AI adapters: connectors to vector stores, RAG, observability, agents, MCP, and caches.

This is the ``sectum.adapters`` namespace package (the engineering spec, section 11).
"""

from sectum.adapters.base import (
    Adapter,
    AdapterFamily,
    AdapterRegistry,
    AgentAdapter,
    AgentResult,
    CacheAdapter,
    Capability,
    EvalSetAdapter,
    MCPAdapter,
    McpResult,
    MemoryAdapter,
    ModelAdapter,
    ObservabilityAdapter,
    RagAnswer,
    RAGPipelineAdapter,
    SearchIndexAdapter,
    TraceHit,
    VectorHit,
    VectorStoreAdapter,
)
from sectum.adapters.fakes import (
    FakeAgent,
    FakeCache,
    FakeEvalSet,
    FakeMCP,
    FakeMemory,
    FakeModel,
    FakeObservability,
    FakeRAGPipeline,
    FakeSearchIndex,
    FakeVectorStore,
)

__all__ = [
    "Adapter",
    "AdapterFamily",
    "AdapterRegistry",
    "AgentAdapter",
    "AgentResult",
    "CacheAdapter",
    "Capability",
    "EvalSetAdapter",
    "FakeAgent",
    "FakeCache",
    "FakeEvalSet",
    "FakeMCP",
    "FakeMemory",
    "FakeModel",
    "FakeObservability",
    "FakeRAGPipeline",
    "FakeSearchIndex",
    "FakeVectorStore",
    "MCPAdapter",
    "McpResult",
    "MemoryAdapter",
    "ModelAdapter",
    "ObservabilityAdapter",
    "RAGPipelineAdapter",
    "RagAnswer",
    "SearchIndexAdapter",
    "TraceHit",
    "VectorHit",
    "VectorStoreAdapter",
]
