"""Sectum AI data models and JSON Schema (the ``sectum_ai.spec`` namespace package)."""

from sectum_ai.spec._logging import configure_logging, get_logger, redact_sensitive
from sectum_ai.spec.enums import (
    AccessOutcome,
    ClassVerdict,
    Confidence,
    CoverageVerdict,
    FindingStatus,
    Grade,
    MarkerType,
    PrincipalKind,
    ScoreScope,
    Severity,
    Surface,
    SurfaceProvenance,
)
from sectum_ai.spec.errors import (
    AdapterError,
    ConfigError,
    DetectionError,
    ErasureUnsupported,
    EvidenceError,
    SectumError,
)
from sectum_ai.spec.hashing import canonical_hash, sha256_hex, to_canonical_json
from sectum_ai.spec.models import (
    SCHEMA_VERSION,
    ClassScore,
    ControlMapping,
    CorpusDocument,
    EvidencePack,
    Finding,
    GroundTruthManifest,
    IsolationScore,
    Marker,
    Observation,
    PlantedLocation,
    Principal,
    ProbeStep,
    RunMetrics,
    RunResult,
    Scenario,
    SectumModel,
    SharedEntity,
    Substrate,
    SyntheticTenantSpec,
    SyntheticUserSpec,
)
from sectum_ai.spec.schema import json_schemas, write_json_schemas
from sectum_ai.spec.stats import normal_quantile, rate_from_counts, wilson_interval
from sectum_ai.spec.text import (
    normalize_for_match,
    ordered_within_span,
    residual_present,
    tokenize,
    untrusted,
)

__all__ = [
    "SCHEMA_VERSION",
    "AccessOutcome",
    "AdapterError",
    "ClassScore",
    "ClassVerdict",
    "Confidence",
    "ConfigError",
    "ControlMapping",
    "CorpusDocument",
    "CoverageVerdict",
    "DetectionError",
    "ErasureUnsupported",
    "EvidenceError",
    "EvidencePack",
    "Finding",
    "FindingStatus",
    "Grade",
    "GroundTruthManifest",
    "IsolationScore",
    "Marker",
    "MarkerType",
    "Observation",
    "PlantedLocation",
    "Principal",
    "PrincipalKind",
    "ProbeStep",
    "RunMetrics",
    "RunResult",
    "Scenario",
    "ScoreScope",
    "SectumError",
    "SectumModel",
    "Severity",
    "SharedEntity",
    "Substrate",
    "Surface",
    "SurfaceProvenance",
    "SyntheticTenantSpec",
    "SyntheticUserSpec",
    "canonical_hash",
    "configure_logging",
    "get_logger",
    "json_schemas",
    "normal_quantile",
    "normalize_for_match",
    "ordered_within_span",
    "rate_from_counts",
    "redact_sensitive",
    "residual_present",
    "sha256_hex",
    "to_canonical_json",
    "tokenize",
    "untrusted",
    "wilson_interval",
    "write_json_schemas",
]
