#!/usr/bin/env python
"""Generate a ``probe.yaml`` manifest beside each probe module (the engineering
spec, section 7.0: "Each probe ships with ... a manifest (probe.yaml)").

The manifest is a declarative mirror of the probe's class attributes, so the
catalog can be consumed without importing Python (dashboards, the suite
selector, external tooling). The Python class attributes remain authoritative;
``tests/unit/test_probe_manifests.py`` fails if a manifest drifts from them.

Run from the repo root:  ``uv run python scripts/gen_probe_manifests.py``
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

import sectum.probes as probes

# Probes that run as a standalone statistical/erasure workflow rather than the
# plan/detect protocol, so they carry no class-level `surfaces`/`requires_adapters`.
# Their surfaces are declared here for the manifest (informational, not class-bound).
_WORKFLOW_SURFACES: dict[str, list[str]] = {
    "kv-cache-timing": ["kv_cache"],
    "gdpr-erasure-verification": [
        "vector_db",
        "tracing",
        "agent_memory",
        "semantic_cache",
        "model_adapter",
        "search_index",
        "eval_set",
    ],
}
_WORKFLOW_REQUIRES: dict[str, list[str]] = {
    "kv-cache-timing": ["model"],
    "gdpr-erasure-verification": ["vector_store"],
}

# id -> runnable example directory (omitted where a probe has no dedicated demo).
_EXAMPLE: dict[str, str] = {
    "agent-framework-hijack": "examples/agent-framework-hijack",
    "agent-tool-hijack": "examples/agent-tool-hijack",
    "embedding-inversion": "examples/embedding-inversion",
    "gdpr-erasure-verification": "examples/erasure-attestation",
    "ikea-extraction": "examples/ikea-extraction",
    "kv-cache-timing": "examples/kv-cache-timing",
    "lora-cross-tenant": "examples/lora-cross-tenant",
    "memory-contamination": "examples/memory-contamination",
    "rag-entity-bleed": "examples/retrieval-pivot",
    "rag-poisoning": "examples/rag-poisoning",
    "semantic-cache-contamination": "examples/semantic-cache",
    "tenant-boundary-fetch": "examples/tenant-boundary-fetch",
}

_HEADER = (
    "# Generated by scripts/gen_probe_manifests.py - do not edit by hand.\n"
    "# A declarative mirror of the probe's class attributes (the engineering\n"
    "# spec, section 7.0); tests/unit/test_probe_manifests.py enforces parity.\n"
)


def _surfaces(cls: type) -> list[str]:
    surfaces = getattr(cls, "surfaces", None)
    if surfaces:
        return [getattr(s, "value", s) for s in surfaces]
    return list(_WORKFLOW_SURFACES.get(cls.id, []))


def _manifest(cls: type) -> dict[str, Any]:
    is_workflow = not hasattr(cls, "surfaces")
    manifest: dict[str, Any] = {
        "id": cls.id,
        "name": cls.name,
        "kind": "workflow" if is_workflow else "plan-detect",
        "owasp_llm": cls.owasp_llm,
        "atlas_techniques": list(cls.atlas_techniques),
        "nist_rmf": list(cls.nist_rmf),
        "surfaces": _surfaces(cls),
        "requires_adapters": (
            list(getattr(cls, "requires_adapters", _WORKFLOW_REQUIRES.get(cls.id, [])))
        ),
    }
    if cls.id in _EXAMPLE:
        manifest["example"] = _EXAMPLE[cls.id]
    return manifest


def _probe_classes() -> list[type]:
    classes = []
    for name in probes.__all__:
        obj = getattr(probes, name)
        if isinstance(obj, type) and getattr(obj, "id", None) and hasattr(obj, "owasp_llm"):
            classes.append(obj)
    return classes


def main() -> int:
    written = 0
    for cls in _probe_classes():
        module = sys.modules[cls.__module__]
        manifest_path = Path(module.__file__).parent / "probe.yaml"
        body = yaml.safe_dump(_manifest(cls), sort_keys=False, default_flow_style=False)
        manifest_path.write_text(_HEADER + body)
        print(f"wrote {manifest_path.relative_to(Path.cwd())}")
        written += 1
    print(f"\n{written} probe manifests generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
