"""Sectum AI data models and JSON Schema (the ``sectum.spec`` namespace package)."""

from sectum.spec.enums import FindingStatus, MarkerType, PrincipalKind, Severity, Surface
from sectum.spec.errors import (
    AdapterError,
    ConfigError,
    DetectionError,
    ErasureUnsupported,
    EvidenceError,
    SectumError,
)
from sectum.spec.hashing import canonical_hash, sha256_hex, to_canonical_json
from sectum.spec.models import (
    SCHEMA_VERSION,
    ControlMapping,
    CorpusDocument,
    EvidencePack,
    Finding,
    GroundTruthManifest,
    Marker,
    Observation,
    PlantedLocation,
    Principal,
    ProbeStep,
    RunMetrics,
    RunResult,
    Scenario,
    SectumModel,
    SharedEntity,
    Substrate,
    SyntheticTenantSpec,
    SyntheticUserSpec,
)
from sectum.spec.schema import json_schemas, write_json_schemas

__all__ = [
    "SCHEMA_VERSION",
    "AdapterError",
    "ConfigError",
    "ControlMapping",
    "CorpusDocument",
    "DetectionError",
    "ErasureUnsupported",
    "EvidenceError",
    "EvidencePack",
    "Finding",
    "FindingStatus",
    "GroundTruthManifest",
    "Marker",
    "MarkerType",
    "Observation",
    "PlantedLocation",
    "Principal",
    "PrincipalKind",
    "ProbeStep",
    "RunMetrics",
    "RunResult",
    "Scenario",
    "SectumError",
    "SectumModel",
    "Severity",
    "SharedEntity",
    "Substrate",
    "Surface",
    "SyntheticTenantSpec",
    "SyntheticUserSpec",
    "canonical_hash",
    "json_schemas",
    "sha256_hex",
    "to_canonical_json",
    "write_json_schemas",
]
